### ISSUE TITLE
Things to Add :)

### ISSUE THREAD

**Issue by saranonearth** [devgrpnitkkr/Techspardha19#2]
Required UI Changes to be made : 
- [x] PROGRESS BAR
> The progress bar loads before every time any component renders. For example when clicking /events before rendering /events route the progress bar should load for some interval saying "loading /events" and then render the component.

- [x] Film Grains Effect
> Already implemented but the the overlay is getting on top off all. Try adding a div with class .overlay. Need to send to the back (Damn)

- [x] Design About Page

- [x] Add Events details in Event Page

- [x] Design Sponsors Page

- [x] Design Faq Page

- [x] Design Ask Queries Page

- [x] Design Contact Page

- [x] Onboard component implementation

- [x] Techspardha Logo Animation

- [x] Sound Effects

- [x] Hover Effects on Home Page

- [x] Techspardhs Events Schedule

Everyone mention which pages you are going to work on!!

**Comment by saranonearth** [comment]
Contact, Ask for queries

**Comment by prathamzx** [comment]
Me and Mayank working on typewriter effect

**Comment by saranonearth** [comment]
events

**Comment by saranonearth** [comment]
onboard
